baseURL = "https://yazeed1s.github.io/blog/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Yazeed.dev"
theme = "gokarna"
enableRobotsTXT = true
enableEmoji = true
pygmentsStyle = "github-dark"
canonifyURLs = true

[params]
description = "I move bytes around!"
avatarURL = "/images/b.png"
AvatarAltText = "avatar"
avatarSize = "size-s"
accentColor = "#8BB8D0"
# showPostsOnHomePage = ""
metaKeywords = ["blog", "gokarna", "hugo"]
togglePreviousAndNextButtons = "true"
customHeadHTML = """
	
	"""
socialIcons = [
	{ name = "twitter", url = "https://twitter.com/yazeed4in" },
	{ name = "github", url = "https://github.com/yazeed1s" },
	{ name = "discord", url = "https://discordapp.com/users/" },
]
# metaKeywords = ["blog", "gokarna", "hugo"]
[menu]
[[menu.main]]
name = "Home"
pre = "<span data-feather='home'></span>"
url = "/blog/"
weight = 1

[[menu.main]]
name = "Posts"
pre = "<span data-feather='book'></span>"
url = "/blog/posts/"
weight = 2

[[menu.main]]
#identifier = "tags"
name = "Tags"
pre = "<span data-feather='tag'></span>"
url = "/blog/tags/"
weight = 3

[[menu.main]]
name = "Projects"
pre = "<span data-feather='code'></span>"
url = "/blog/projects/"
weight = 4

[[menu.main]]
name = "github"
pre = "<span data-feather='github'></span>"
url = "https://github.com"
weight = 5


[markup]
[markup.tableOfContents]
startLevel = 1
endLevel = 4
ordered = false
